services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: 7476c2f22a3f28b64a9abe9d69855ce73c8cf4276de0598563233b574e1d2a2a
      ALGORITHM: HS256
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/banking
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: